Add to_message to Interactions::Message
shardlab/discordrb pull request #155
Opened 2022-05-01 05:00 UTC by dylhack

# Summary

This would create a shortcut to using all of the methods that are available for Discordrb::Message

## Added

  - Added Interactions::Message#to_message (2c87b416a89efd2c705fbe20bd81128fe22dfa6d)
  - Added to_message to Discordrb::Message (0970ff27c2a70b26e0092af3fafff107651aae86)
  
 Adding to_message to Discordrb::Message was in inspiration of Ruby's String#to_s method.

2022-05-01 05:22 UTC, dylhack commented
note: The hash of the data parameter in Interactions::Message is missing `referenced_message`.

2022-05-01 13:02 UTC, Daniel-Worrall requested changes
Please remove the aliases, they don't fit with the rest of the library (consistency is very important)

Otherwise, the code seems fine, though it comes into question why store the data as well as everything it contains.

This should probably be reworked to contain a message object if possible, and use delegated properties instead of bringing everything to the Interaction object itself.
Not a fault of the PR, just a design decision we may not want to lock ourselves into that I only just caught since I haven't had any chance to look at Interactions

Opinions, @swarley?

2022-05-01 13:02 UTC, Daniel-Worrall commented on lib/discordrb/data/interaction.rb
> +      alias_method :to_m, :to_message
This alias doesn't go with the rest of our codebase, we don't use any `to_x` single letter aliases beyond the stdlib stuff

2022-05-01 13:02 UTC, Daniel-Worrall commented on lib/discordrb/data/message.rb
> +    alias_method :to_m, :to_message
ditto

2022-05-01 13:21 UTC, swarley commented
I think the data storage is fine, we want to be lazy here. I'm not a fan of the `to_m`. I would prefer just `#message` because I believe it's the most consistent

2022-05-01 20:54 UTC, dylhack commented on lib/discordrb/data/message.rb
> +    alias_method :to_m, :to_message
resolved in 93f13b52d1b471bdd1f1f9313f50dc62fa4e8df4

2022-05-01 20:54 UTC, dylhack commented on lib/discordrb/data/interaction.rb
> +      alias_method :to_m, :to_message
resolved in 93f13b52d1b471bdd1f1f9313f50dc62fa4e8df4

2022-10-09 12:46 UTC, Daniel-Worrall approved these changes
LGTM 👍

2022-10-09 20:10 UTC, dylhack commented
Awesome!

2022-10-09 20:11 UTC, swarley commented
Thank you!

2022-10-09 20:11 UTC, merged