Allow disconnect user from a voice channel via the Server#move method
shardlab/discordrb pull request #226
Opened 2023-06-07 17:16 UTC by Dakurei

# Summary

It's all in the title
Allows to fix issue #185 

---

## Changed
- Server#move accept nil for channel param

2023-06-07 18:19 UTC, anna328p requested changes
otherwise LGTM

2023-06-07 18:19 UTC, anna328p commented on lib/discordrb/data/server.rb
> +    # Can't move user if he's not already connected to a server voice channel.
May be better to rephrase this, merging it with the other requirement for this call and avoiding generic pronouns. e.g.

```ruby
# Forcibly moves a user into a different voice channel.
# Only works if the bot has the permission needed and if the user is already connected to some voice channel on this server.
```

2023-06-13 22:43 UTC, anna328p approved these changes

2023-06-13 22:57 UTC, swarley approved these changes

2023-06-13 22:57 UTC, merged