Allow supressing embeds on Message
shardlab/discordrb pull request #240
Opened 2023-10-14 13:45 UTC by Quintasan

# Summary

* Add `pry-byebug` to development dependencies
* Add `API::Channel#suppress_embeds`
* Add `Message#suppress_embeds`

2024-10-14 07:04 UTC, Droid00000 requested changes
Mainly looks good just needs a few minor changes. The main thing is that I'd say the `pry-byebug` dependency isn't really needed and goes way beyond the scope of this PR.

2024-10-14 07:04 UTC, Droid00000 commented on lib/discordrb/data/message.rb
> +      response = API::Channel.suppress_embeds(@bot.token, @channel.id, @id)
I believe it might be better to wrap the entire API call in in ``JSON.parse``. i.e. ``JSON.parse(API::Channel.suppress_embeds(@bot.token, @channel.id, @id))

2024-10-14 07:04 UTC, Droid00000 commented on discordrb.gemspec
> +  spec.add_development_dependency 'pry-byebug'
I don't think this dependency is really needed, but, if there is, feel-free to start a discussion in the [drb channel.](https://discord.gg/discord-api)

2024-10-14 11:07 UTC, Quintasan commented
> Mainly looks good just needs a few minor changes. The main thing is that I'd say the `pry-byebug` dependency isn't really needed and goes way beyond the scope of this PR.

We should be good to go now

2024-10-14 17:29 UTC, Droid00000 commented
> > Mainly looks good just needs a few minor changes. The main thing is that I'd say the `pry-byebug` dependency isn't really needed and goes way beyond the scope of this PR.
> 
> 
> 
> We should be good to go now

Almost there, I think you forgot to remove the dependency from the spec dependency though 😅

2024-10-14 20:19 UTC, Droid00000 approved these changes

2024-11-12 21:14 UTC, Quintasan commented
@Droid00000 well, this should be good now

2024-11-29 22:08 UTC, wouterdedroog commented
Looks great! It could be interesting to use this PR to further implement message flags (in a similar way to how the permissions class is currently structured). This is what I came up with: https://gist.github.com/wouterdedroog/59ed3076558c6d943dca5f8c75d5437f

2024-12-10 10:49 UTC, Quintasan commented
@Droid00000 bump

2024-12-10 15:37 UTC, swarley commented
Would you be open to doing the API portion through a message update rather than a dedicated API method? I don't want to add an API level method for every flag that may need to be updated. Just something like
```ruby
flags = @flags | SUPPRESS_EMBEDS
API::Channel.edit_message(..., flags)
```

2024-12-10 22:22 UTC, Quintasan commented
> Would you be open to doing the API portion through a message update rather than a dedicated API method? I don't want to add an API level method for every flag that may need to be updated. Just something like
> 
> ```ruby
> flags = @flags | SUPPRESS_EMBEDS
> API::Channel.edit_message(..., flags)
> ```

I most certainly don't mind, but I'd like to work on this incrementally. When this gets merged, then I'll prepare another PR

2025-01-07 15:47 UTC, merged